using grate.Infrastructure;

namespace grate.Oracle.Infrastructure;

public readonly struct OracleSyntax : ISyntax
{
    private static readonly IStatementSplitter _statementSplitter = new OracleStatementSplitter();
    public IStatementSplitter StatementSplitter => _statementSplitter;

    public string CurrentDatabase => "select user from dual";
    public string ListDatabases => "SELECT * FROM all_users";

    public string CreateDatabase(string userName, string? password) => $@"
begin 
    execute immediate 'CREATE USER {userName} IDENTIFIED BY ""{password}""';
    execute immediate 'GRANT ALL PRIVILEGES TO {userName}';
end;
";
    public string DropDatabase(string databaseName) => $@"
begin 
    DECLARE
       usr VARCHAR2 (32) := '{databaseName}';
    BEGIN
       FOR ln_cur IN (SELECT sid, serial# FROM v$session WHERE username = usr)
       LOOP
          EXECUTE IMMEDIATE ('ALTER SYSTEM KILL SESSION ''' || ln_cur.sid || ',' || ln_cur.serial# || ''' IMMEDIATE');
          EXECUTE IMMEDIATE ('ALTER SYSTEM DISCONNECT SESSION ''' || ln_cur.sid || ',' || ln_cur.serial# || ''' IMMEDIATE');
       END LOOP;
    END;

    EXECUTE IMMEDIATE 'DROP USER {databaseName} CASCADE';
end;
";
    public string TableWithSchema(string schemaName, string tableName) => $"{schemaName}_{tableName}";
    public string ReturnId => "RETURNING id;";
    public string LimitN(string sql, int n) => sql + $"\nLIMIT {n}";
    public string ResetIdentity(string schemaName, string tableName, long _) => $"ALTER TABLE {TableWithSchema(schemaName, tableName)} MODIFY id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE)";
}
